# Generated by Django 4.1.7 on 2023-06-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consominus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='numeroClien',
            new_name='numeroClient',
        ),
    ]
